### ISSUE TITLE
Remove dependence on QColor from all messages

### ISSUE THREAD

**Issue by SmirnoffYM** [SmirnoffYM/AI-simulator#11]
We need to write hub without any dependencies on Qt, so I've added new class called Color. Your task will be to remove all QColor objects from all messages. To do this, you must implement constructor converting color from std::string to rgb.

**Comment by Minoru** [comment]
We don't really need this as binary protocol uses separate fields for red, green and blue.

**Comment by SmirnoffYM** [comment]
Okay, that's good.
