### ISSUE TITLE
Agent ID чи невеличка зміна архітектури?

### ISSUE THREAD

**Issue by Minoru** [SmirnoffYM/AI-simulator#2]
При проектуванні взаємодії між модулями ми не врахували одну деталь: коли com отримує повідомлення, він якимось чином повинен здогадатись, від якого агента воно прийшло. Проблему можна вирішити двома методами:
1. Додати відповідне поле (agent ID) до мережевого протоколу і таким чином перекласти проблему на агентів. Перевага такого рішення — простота, недолік — доведеться якимось чином повідомляти агентам їх ID.
2. Передавати у модуль com список пар (port, ID). Це трохи ускладнить архітектуру (додатковий параметр у конструкторі ComModule) і код (на данний момент все складається так, що після прийому повідомлення com просто серіалізує JSON у QObject і поміщає у чергу; якщо додати згаданий список, доведеться також робити пошук ID по порту).

Яке рішення обрати?

**Comment by OblamskyiV** [comment]
,        -     ID =
__?

2012/3/10 Alexander Batischev <
reply@reply.github.com

**Comment by SmirnoffYM** [comment]
Додати відповідне поле (agent ID) до мережевого протоколу і таким чином перекласти проблему на агентів. Перевага такого рішення — простота, недолік — доведеться якимось чином повідомляти агентам їх ID.

ID агента - це його порт, він зберігається в текстовому профайлі. Тому варіант 1.
